# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81c5c5685d5a42a40772cacabb0868011f973d553f2191b622a8a4dd161ac35ede98723ede32b1ff75bffbc0382a5c088ef0708768de0b41fe3743c87b2ea0a8

test:
  secret_key_base: 552dba8f49459fe3ba0e61c6ab185a0d17b82d411fb78e874562fabab2e849d16398bdd81f29b1f9e637e339738a8898ebe18a196c41c0483c8e6134898b6d98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
